### ISSUE TITLE
Feature request: server banner

### ISSUE THREAD

**Issue by ch4r13** [Blockfluit/webstatistics#1]
Hello,
For the first I want to thank you for your effort to make this beautiful plugin. I don't now if you are still working on this, or if you have any plans to continue, but if so. Please make an option to put banner on the website to specific link. Something similar to dynmap where you can put server banner. 
and again, 

Thanks for your effort, I really appreciate it !

**Comment by Blockfluit** [comment]
Thank you for the compliment! Always nice to hear when your work is appreciated.

I made this plugin mainly for my own minecraft server, since I could not find a plugin like this. Hence why it is not really that customizable.

At the moment I am working on different projects (not minecraft related). So I simply don't have the time to work on this plugin. If in the future there is a high demand for this plugin and I have the time, I will definitely take you suggestion into consideration. I also would probably completely remake it since it is not really that well written and not up to my current standards.  

nonetheless, thanks for the suggestion.
