### ISSUE TITLE
How To Integrate Old Statistics

### ISSUE THREAD

**Issue by JasonDykstra** [Blockfluit/webstatistics#2]
Hello,

I recently installed this plugin to my server and it works great! However, it only tracks statistics created *after* the plugin was installed. Is there any way to incorporate the statistics that were generated since the server's creation? Thanks in advance for your help!

**Comment by Blockfluit** [comment]
Great to hear it still works! Haven't worked at it sinced I released the first build. But to anwser your question, this plugin works by reading all the json files inside the stats folder. These files store all stats from the corresponding user since the generation of the world. This stats folder is located inside the world folder. So lets say you delete the world folder because maybe you want to start over again, you also delete all the user stats. Since I don't know exactly what you have done, I am guessing you've done something like that.

I hope this anwsers your question. If not, feel free to further clarify your problem.
